### ISSUE TITLE
Font rendering issues (Fontconfig error when starting Sourcetrail)

### ISSUE THREAD

**Issue by cjustin88** [CoatiSoftware/SourcetrailBugTracker#518]
DPI scaling issue:
When using Sourcetrail on my laptop's screen (1920x1080, 157 ppi), the font is legible:
![screenshot from 2017-11-10 13-21-30](https://user-images.githubusercontent.com/5272255/32679146-2b252f48-c61a-11e7-9bf5-d5ed8722d338.png)
but when I drag it to my external monitor (1920x1200, 94 ppi), the font becomes very small
![screenshot from 2017-11-10 13-20-29](https://user-images.githubusercontent.com/5272255/32679242-83d34544-c61a-11e7-9bd6-2ca92b1f8217.png)
:
Is this the expected scaling behaviour? I thought that the physical size of the font on the lower PPI screen should be larger, but it in fact becomes smaller. When looking at both screenshots at the same scaling, the font is indeed rendered at a smaller size on the lower PPI screen than on the higher screen.

Font config issue:
Sourcetrail seems to have some trouble loading the font so it defaults to the Monospace font? For instance:
![screenshot from 2017-11-10 13-29-31](https://user-images.githubusercontent.com/5272255/32679414-3990d888-c61b-11e7-8de4-a614046f8ac3.png)
does not look like the font used in the screenshots on Sourcetrail page (and it doesn't look like Source Code Pro which is what it defaulted to).
When I launch Sourcetrail, I get this warning:
```
➜  Sourcetrail sourcetrail
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```
(the contents of 10-scale-bitmap-fonts.conf is at the end of this message)

I do have Source Code Pro installed:
```
➜  ~ fc-list
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-BlackIt.otf: Source Code Pro,Source Code Pro Black:style=Black Italic,Italic
/usr/share/fonts/lyx/eufm10.ttf: eufm10:style=LyX
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-LightIt.otf: Source Code Pro,Source Code Pro Light:style=Light Italic,Italic
/usr/share/fonts/lyx/cmsy10.ttf: cmsy10:style=LyX
/usr/share/fonts/lyx/msam10.ttf: msam10:style=LyX
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Bold.otf: Source Code Pro:style=Bold
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Regular.otf: Source Code Pro:style=Regular
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Medium.otf: Source Code Pro,Source Code Pro Medium:style=Medium,Regular
/usr/share/fonts/lyx/cmmi10.ttf: cmmi10:style=LyX
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-MediumIt.otf: Source Code Pro,Source Code Pro Medium:style=Medium Italic,Italic
/usr/share/X11/fonts/Type1/c0611bt_.pfb: Courier 10 Pitch:style=Bold Italic
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Light.otf: Source Code Pro,Source Code Pro Light:style=Light,Regular
/usr/share/X11/fonts/Type1/UTBI____.pfa: Utopia:style=Bold Italic
/usr/share/X11/fonts/Type1/c0419bt_.pfb: Courier 10 Pitch:style=Regular
/usr/share/fonts/lyx/wasy10.ttf: wasy10:style=LyX
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Black.otf: Source Code Pro,Source Code Pro Black:style=Black,Regular
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-ExtraLight.otf: Source Code Pro,Source Code Pro ExtraLight:style=ExtraLight,Regular
/usr/share/X11/fonts/Type1/c0648bt_.pfb: Bitstream Charter:style=Regular
/usr/share/fonts/lyx/esint10.ttf: esint10:style=LyX
/usr/share/fonts/lyx/rsfs10.ttf: rsfs10:style=LyX
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-BoldIt.otf: Source Code Pro:style=Bold Italic
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-ExtraLightIt.otf: Source Code Pro,Source Code Pro ExtraLight:style=ExtraLight Italic,Italic
/usr/share/fonts/lyx/stmary10.ttf: stmary10:style=LyX
/usr/share/X11/fonts/Type1/cursor.pfa: Cursor:style=Regular
/usr/share/X11/fonts/Type1/UTB_____.pfa: Utopia:style=Bold
/usr/share/fonts/lyx/cmex10.ttf: cmex10:style=LyX
/usr/share/X11/fonts/Type1/c0583bt_.pfb: Courier 10 Pitch:style=Bold
/usr/share/X11/fonts/Type1/UTI_____.pfa: Utopia:style=Italic
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-SemiboldIt.otf: Source Code Pro,Source Code Pro Semibold:style=Semibold Italic,Italic
/usr/share/X11/fonts/Type1/c0582bt_.pfb: Courier 10 Pitch:style=Italic
/usr/share/fonts/lyx/msbm10.ttf: msbm10:style=LyX
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-It.otf: Source Code Pro:style=Italic
/usr/share/X11/fonts/Type1/c0633bt_.pfb: Bitstream Charter:style=Bold Italic
/usr/share/X11/fonts/Type1/c0649bt_.pfb: Bitstream Charter:style=Italic
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Semibold.otf: Source Code Pro,Source Code Pro Semibold:style=Semibold,Regular
/usr/share/X11/fonts/Type1/c0632bt_.pfb: Bitstream Charter:style=Bold
/usr/share/fonts/lyx/cmr10.ttf: cmr10:style=LyX
/usr/share/X11/fonts/Type1/UTRG____.pfa: Utopia:style=Regular
```
What could be the issue?

I am using Sourcetrail in a X session forwarded over SSH (i.e. ssh myserver with ForwardX11 yes, and then run sourcetrail). Could this be the issue? The SSH client here is Fedora 26 (GNOME with Wayland), and the SSH server running Sourcetrail is RHEL 7.4.

`/etc/fonts/conf.d/10-scale-bitmap-fonts.conf`:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>

<match target="font">
  <test name="scalable" compare="eq">
    <bool>false</bool>
  </test>
  <edit name="pixelsizefixupfactor" mode="assign">
    <divide>
      <name target="pattern">pixelsize</name>
      <name target="font"   >pixelsize</name>
    </divide>
  </edit>
</match>
<match target="font">
  <test name="scalable" compare="eq">
    <bool>false</bool>
  </test>
  <edit name="scalingnotneeded" mode="assign">
    <and>
      <less>
        <name>pixelsizefixupfactor</name>
        <double>1.2</double>
      </less>
      <more>
        <name>pixelsizefixupfactor</name>
        <double>0.8</double>
      </more>
    </and>
  </edit>
</match>
<!--
  So far we determined the scale factor.  Now, check and if
  scaling is NOT desirable, just reset the scale factor to 1.0.
  -->
<match target="font">
  <test name="scalable" compare="eq">
    <bool>false</bool>
  </test>
  <test name="pixelsize" target="pattern" compare="less">
    <double>64</double>
  </test>
  <test name="hinting" compare="eq">
    <bool>true</bool>
  </test>
  <test name="scalingnotneeded" compare="eq">
    <bool>true</bool>
  </test>
  <edit name="pixelsizefixupfactor" mode="assign">
    <double>1.0</double>
  </edit>
</match>
<!--
  If we *are* going to scale, go ahead and do it.
  -->
<match target="font">
  <test name="scalable" compare="eq">
    <bool>false</bool>
  </test>
  <test name="pixelsizefixupfactor" compare="not_eq">
    <double>1.0</double>
  </test>
  <edit name="matrix" mode="assign">
    <times>
      <name>matrix</name>
      <matrix>
        <name>pixelsizefixupfactor</name> <double>0</double>
        <double>0</double> <name>pixelsizefixupfactor</name>
       </matrix>
    </times>
  </edit>
  <edit name="size" mode="assign">
    <divide>
      <name>size</name>
      <name>pixelsizefixupfactor</name>
    </divide>
  </edit>
</match>

</fontconfig>
```

**Comment by egraether** [comment]
Thanks for reporting these issues!

Session forwarding could be related to the scaling issue. Also using screens with different DPI simultaneously.

You can change font size within the main UI in the **Preferences** or with `Ctrl + +/-`, which will improve the situation a bit.

I just checked and it seems we never really define a font family for the dialogs, Source Code Pro is only used within the main UI, so this should just default to the default screen font. I don't think the errors related to font config have anything to do with it tough. Do you see the same problem in all dialogs e.g. within **Preferences** or **New Project** dialogs?

**Comment by Bagira80** [comment]
I am having the same problems.

However, I am using it directly on my Ubuntu 16.04 laptop, not via an SSH connection. I have a two-monitor setup:
* The left panel has 1920x1080 Pixels,
* the right panel has 2560x1440 Pixels.

Some observations:
* On the left panel, the general GUI uses way too large fonts and buttons.
* On the right panel, the general GUI seem to be using correctly sized fonts and buttons.
* On the left panel, the "close" and "enlarge" buttons in the top right corners of the inner windows are correctly sized.
* On the right panel, the "close" and "enlarge" buttons in the top right corners of the inner windows are way too small.
* On the left panel system-windows (like FileOpen-dialogs and status-message windows) have way too large GUI-elements but correctly sized fonts.
* On the right panel system-windows (like FileOpen-dialogs and status-message windows) have correctly sized GUI-elements but way too small fonts.

Example 1: Program on left side, FileOpen-dialog from left side, too.
![Example1](https://user-images.githubusercontent.com/1121753/33210989-b8770274-d11c-11e7-9ba4-6e08e60c4dd6.png)

Example 2: Program on left side, FileOpen-dialog from right side.
![Example2](https://user-images.githubusercontent.com/1121753/33210990-b88f7214-d11c-11e7-80a3-0587ad9c89e3.png)

Example 3: Program on right side, FileOpen-dialog from right side. Everything looks ok, except for the "close" and "enlarge" buttons of the inner windows and the font used in the FileOpen-dialog.
![Example3](https://user-images.githubusercontent.com/1121753/33211379-8df57998-d11e-11e7-8143-9b3dd8292ec6.png)

**Comment by Bagira80** [comment]
Oh, and one additional note: When Sourcetrail starts it prints these messages:
```
/usr/bin/sourcetrail: 8: /usr/bin/sourcetrail: [[: not found
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
```

The first error is unrelated to the rendering issue.  

It is due to the fact that shell-script `/usr/bin/sourcetrail` uses `/bin/sh` in its shebang (`#!`), which on my system is a symlink to `/bin/dash` which does not know the `[[` command.  
You probably should either use the traditional shell commands or instead use a specific shell like `/bin/bash` which supports commands `[[` and `]]`.
 

However, the font-errors probably have something to do with the rendering issue.

**Comment by egraether** [comment]
@Bagira80 Thanks for the infos!

The issue with `[[` is already fixed: #519 
There's another open issue for the font loading: #518

**Comment by Bagira80** [comment]
> There's another open issue for the font loading: #518

#518 is this current issue. ;-)

**Comment by egraether** [comment]
Good point :)

**Comment by egraether** [comment]
This issue is related to highDPI scaling. Usually the highDPI scaling is taken care of by Qt by enabling `QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling, true);`, but for some reasons this seems not to work sometimes.

Icon sizes were fixed for these cases with 2017.4.68

**Comment by cjustin88** [comment]
I fixed the scaling on my system by setting environment variables `QT_AUTO_SCREEN_SCALE_FACTOR=0` and `QT_SCALE_FACTOR=1` with font size 12 as documented in https://github.com/CoatiSoftware/SourcetrailBugTracker/issues/523.

Thanks!

**Comment by egraether** [comment]
Thank you for the update!
Is everything the right size for you now? Can you post another screenshot please?

**Comment by Bagira80** [comment]
Using `QT_AUTO_SCREEN_SCALE_FACTOR=0` fixes it for me.  
`QT_SCALE_FACTOR=1` does not change anything for me (so it might be implicit).

**Comment by egraether** [comment]
Thanks for notifying!

**Comment by Bagira80** [comment]
The beta works.

By default, it shows the same problem on my Ubuntu 16.04 system, but after changing the *"Auto Scaling to DPI"* setting to `system` or `off` (which seem to be the same on my system) it looks fine.

Changing the *"Scale Factor"* shows also some effect but is not really useful. (It still shows different sizes on my different screens.)

**Comment by egraether** [comment]
Thanks! I'm closing this now. For new problems please open a new issue.
